package com.miguelcr.cursoandroid.equiposfutbol.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EQUIPO.
 */
public class Equipo {

    private Long id;
    /** Not-null value. */
    private String nombre;
    /** Not-null value. */
    private String escudo;

    public Equipo() {
    }

    public Equipo(Long id) {
        this.id = id;
    }

    public Equipo(Long id, String nombre, String escudo) {
        this.id = id;
        this.nombre = nombre;
        this.escudo = escudo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /** Not-null value. */
    public String getEscudo() {
        return escudo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEscudo(String escudo) {
        this.escudo = escudo;
    }

}
